# Generated by Django 3.2 on 2021-04-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_order_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
